-- PostgreSQL schema for GreenBite.
-- This file is intended to run as an initialization script in Docker and
-- stay compatible with both the current backend implementation and the
-- 2026-04-24 API/document supplements.

BEGIN;

-- =============================
-- 1. Users and permissions
-- =============================
CREATE TABLE IF NOT EXISTS users (
	user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	username VARCHAR(100) NOT NULL UNIQUE,
	password_hash VARCHAR(255) NOT NULL,
	role VARCHAR(20) NOT NULL CHECK (role IN ('customer', 'staff', 'admin')),
	status VARCHAR(20) NOT NULL DEFAULT 'active'
		CHECK (status IN ('active', 'disabled')),
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS user_preferences (
	user_id BIGINT PRIMARY KEY,
	target_calories INT CHECK (target_calories IS NULL OR target_calories >= 0),
	target_protein INT CHECK (target_protein IS NULL OR target_protein >= 0),
	is_vegetarian BOOLEAN NOT NULL DEFAULT FALSE,
	CONSTRAINT fk_user_preferences_user
		FOREIGN KEY (user_id)
		REFERENCES users (user_id)
		ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS allergens (
	allergen_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS user_allergies (
	user_id BIGINT NOT NULL,
	allergen_id BIGINT NOT NULL,
	PRIMARY KEY (user_id, allergen_id),
	CONSTRAINT fk_user_allergies_user
		FOREIGN KEY (user_id)
		REFERENCES users (user_id)
		ON DELETE CASCADE,
	CONSTRAINT fk_user_allergies_allergen
		FOREIGN KEY (allergen_id)
		REFERENCES allergens (allergen_id)
		ON DELETE RESTRICT
);

-- =============================
-- 2. Meals and ingredients
-- =============================
CREATE TABLE IF NOT EXISTS meals (
	meal_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name VARCHAR(150) NOT NULL,
	description TEXT,
	calories INT CHECK (calories IS NULL OR calories >= 0),
	protein INT CHECK (protein IS NULL OR protein >= 0),
	sustainability_score INT CHECK (
		sustainability_score IS NULL
		OR sustainability_score BETWEEN 0 AND 10
	),
	image_url VARCHAR(500),
	is_deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS ingredients (
	ingredient_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name VARCHAR(120) NOT NULL UNIQUE,
	is_deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS meal_ingredients (
	meal_id BIGINT NOT NULL,
	ingredient_id BIGINT NOT NULL,
	weight_g INT NOT NULL CHECK (weight_g > 0),
	PRIMARY KEY (meal_id, ingredient_id),
	CONSTRAINT fk_meal_ingredients_meal
		FOREIGN KEY (meal_id)
		REFERENCES meals (meal_id)
		ON DELETE CASCADE,
	CONSTRAINT fk_meal_ingredients_ingredient
		FOREIGN KEY (ingredient_id)
		REFERENCES ingredients (ingredient_id)
		ON DELETE RESTRICT
);

-- =============================
-- 3. Inventory and tags
-- =============================
-- Batch-based stock records: one ingredient can have multiple records with different expiry dates.
CREATE TABLE IF NOT EXISTS stock_records (
	stock_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	ingredient_id BIGINT NOT NULL,
	current_qty_g INT NOT NULL CHECK (current_qty_g >= 0),
	expiry_date DATE,
	CONSTRAINT fk_stock_records_ingredient
		FOREIGN KEY (ingredient_id)
		REFERENCES ingredients (ingredient_id)
		ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ingredient_allergens (
	ingredient_id BIGINT NOT NULL,
	allergen_id BIGINT NOT NULL,
	PRIMARY KEY (ingredient_id, allergen_id),
	CONSTRAINT fk_ingredient_allergens_ingredient
		FOREIGN KEY (ingredient_id)
		REFERENCES ingredients (ingredient_id)
		ON DELETE CASCADE,
	CONSTRAINT fk_ingredient_allergens_allergen
		FOREIGN KEY (allergen_id)
		REFERENCES allergens (allergen_id)
		ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS sustainability_tags (
	tag_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	tag_name VARCHAR(100) NOT NULL UNIQUE,
	score_weight INT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS meal_sustainability_tags (
	meal_id BIGINT NOT NULL,
	tag_id BIGINT NOT NULL,
	PRIMARY KEY (meal_id, tag_id),
	CONSTRAINT fk_meal_sustainability_tags_meal
		FOREIGN KEY (meal_id)
		REFERENCES meals (meal_id)
		ON DELETE CASCADE,
	CONSTRAINT fk_meal_sustainability_tags_tag
		FOREIGN KEY (tag_id)
		REFERENCES sustainability_tags (tag_id)
		ON DELETE RESTRICT
);

-- =============================
-- 4. Orders and order items
-- =============================
CREATE TABLE IF NOT EXISTS orders (
	order_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	user_id BIGINT NOT NULL,
	recommendation_request_id VARCHAR(64),
	status VARCHAR(20) NOT NULL DEFAULT 'pending'
		CHECK (status IN ('pending', 'confirmed', 'cancelled')),
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	confirmed_at TIMESTAMP,
	cancelled_at TIMESTAMP,
	CONSTRAINT fk_orders_user
		FOREIGN KEY (user_id)
		REFERENCES users (user_id)
		ON DELETE RESTRICT,
	CONSTRAINT chk_orders_status_timestamps CHECK (
		(status = 'pending' AND confirmed_at IS NULL AND cancelled_at IS NULL)
		OR (status = 'confirmed' AND confirmed_at IS NOT NULL AND cancelled_at IS NULL)
		OR (status = 'cancelled' AND cancelled_at IS NOT NULL)
	)
);

CREATE TABLE IF NOT EXISTS order_items (
	order_id BIGINT NOT NULL,
	meal_id BIGINT NOT NULL,
	quantity INT NOT NULL CHECK (quantity > 0),
	meal_name_snapshot VARCHAR(150),
	calories_snapshot INT CHECK (calories_snapshot IS NULL OR calories_snapshot >= 0),
	protein_snapshot INT CHECK (protein_snapshot IS NULL OR protein_snapshot >= 0),
	sustainability_score_snapshot INT CHECK (
		sustainability_score_snapshot IS NULL
		OR sustainability_score_snapshot BETWEEN 0 AND 10
	),
	image_url_snapshot VARCHAR(500),
	PRIMARY KEY (order_id, meal_id),
	CONSTRAINT fk_order_items_order
		FOREIGN KEY (order_id)
		REFERENCES orders (order_id)
		ON DELETE CASCADE,
	CONSTRAINT fk_order_items_meal
		FOREIGN KEY (meal_id)
		REFERENCES meals (meal_id)
		ON DELETE RESTRICT
);

-- Keep the current backend code working while preserving documented order
-- timestamps. The Java code only updates `status`, so the trigger backfills
-- the matching timestamp fields automatically.
CREATE OR REPLACE FUNCTION trg_sync_order_status_timestamps()
RETURNS TRIGGER AS $$
DECLARE
	old_confirmed_at TIMESTAMP;
	old_cancelled_at TIMESTAMP;
BEGIN
	IF TG_OP = 'UPDATE' THEN
		old_confirmed_at := OLD.confirmed_at;
		old_cancelled_at := OLD.cancelled_at;
	END IF;

	IF NEW.status = 'pending' THEN
		NEW.confirmed_at := NULL;
		NEW.cancelled_at := NULL;
	ELSIF NEW.status = 'confirmed' THEN
		NEW.confirmed_at := COALESCE(NEW.confirmed_at, old_confirmed_at, CURRENT_TIMESTAMP);
		NEW.cancelled_at := NULL;
	ELSIF NEW.status = 'cancelled' THEN
		NEW.cancelled_at := COALESCE(NEW.cancelled_at, old_cancelled_at, CURRENT_TIMESTAMP);
	END IF;
	RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_orders_sync_status_timestamps ON orders;
CREATE TRIGGER trg_orders_sync_status_timestamps
BEFORE INSERT OR UPDATE ON orders
FOR EACH ROW
EXECUTE FUNCTION trg_sync_order_status_timestamps();

-- Preserve order snapshots for future order-detail/report use, while allowing
-- the current mapper to insert only `order_id`, `meal_id`, `quantity`.
CREATE OR REPLACE FUNCTION trg_fill_order_item_snapshots()
RETURNS TRIGGER AS $$
DECLARE
	src_meal meals%ROWTYPE;
BEGIN
	SELECT *
	INTO src_meal
	FROM meals
	WHERE meal_id = NEW.meal_id;

	IF src_meal.meal_id IS NULL THEN
		RAISE EXCEPTION 'meal % not found when filling order snapshot', NEW.meal_id;
	END IF;

	NEW.meal_name_snapshot := COALESCE(NEW.meal_name_snapshot, src_meal.name);
	NEW.calories_snapshot := COALESCE(NEW.calories_snapshot, src_meal.calories);
	NEW.protein_snapshot := COALESCE(NEW.protein_snapshot, src_meal.protein);
	NEW.sustainability_score_snapshot := COALESCE(
		NEW.sustainability_score_snapshot,
		src_meal.sustainability_score
	);
	NEW.image_url_snapshot := COALESCE(NEW.image_url_snapshot, src_meal.image_url);

	RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_order_items_fill_snapshots ON order_items;
CREATE TRIGGER trg_order_items_fill_snapshots
BEFORE INSERT OR UPDATE ON order_items
FOR EACH ROW
EXECUTE FUNCTION trg_fill_order_item_snapshots();

-- =============================
-- 5. Recommendation, auth, audit, reports
-- =============================
CREATE TABLE IF NOT EXISTS recommendation_events (
	event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	request_id VARCHAR(64) NOT NULL,
	user_id BIGINT NOT NULL,
	meal_id BIGINT NOT NULL,
	event_type VARCHAR(20) NOT NULL
		CHECK (event_type IN ('exposure', 'click', 'selected')),
	rank_position INT CHECK (rank_position IS NULL OR rank_position > 0),
	order_id BIGINT,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT fk_recommendation_events_user
		FOREIGN KEY (user_id)
		REFERENCES users (user_id)
		ON DELETE CASCADE,
	CONSTRAINT fk_recommendation_events_meal
		FOREIGN KEY (meal_id)
		REFERENCES meals (meal_id)
		ON DELETE RESTRICT,
	CONSTRAINT fk_recommendation_events_order
		FOREIGN KEY (order_id)
		REFERENCES orders (order_id)
		ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS auth_sessions (
	session_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	user_id BIGINT NOT NULL,
	token_hash VARCHAR(255) NOT NULL UNIQUE,
	issued_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	expires_at TIMESTAMP NOT NULL,
	revoked_at TIMESTAMP,
	CONSTRAINT fk_auth_sessions_user
		FOREIGN KEY (user_id)
		REFERENCES users (user_id)
		ON DELETE CASCADE,
	CONSTRAINT chk_auth_sessions_expiry CHECK (expires_at > issued_at)
);

CREATE TABLE IF NOT EXISTS audit_logs (
	audit_log_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	actor_user_id BIGINT,
	action VARCHAR(100) NOT NULL,
	target_type VARCHAR(50),
	target_id VARCHAR(100),
	details JSONB NOT NULL DEFAULT '{}'::jsonb,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT fk_audit_logs_actor
		FOREIGN KEY (actor_user_id)
		REFERENCES users (user_id)
		ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS sustainability_reports (
	report_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	summary TEXT NOT NULL,
	report_data JSONB NOT NULL DEFAULT '{}'::jsonb,
	generated_by BIGINT,
	range_start DATE,
	range_end DATE,
	generated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT fk_sustainability_reports_user
		FOREIGN KEY (generated_by)
		REFERENCES users (user_id)
		ON DELETE SET NULL,
	CONSTRAINT chk_sustainability_reports_range CHECK (
		range_start IS NULL
		OR range_end IS NULL
		OR range_start <= range_end
	)
);

-- =============================
-- Supporting indexes for common joins and lookups
-- =============================
CREATE INDEX IF NOT EXISTS idx_orders_user_id ON orders (user_id);
CREATE INDEX IF NOT EXISTS idx_orders_status_created_at ON orders (status, created_at);
CREATE INDEX IF NOT EXISTS idx_orders_recommendation_request_id
	ON orders (recommendation_request_id);
CREATE INDEX IF NOT EXISTS idx_order_items_order_id ON order_items (order_id);
CREATE INDEX IF NOT EXISTS idx_order_items_meal_id ON order_items (meal_id);
CREATE INDEX IF NOT EXISTS idx_meals_is_deleted ON meals (is_deleted);
CREATE INDEX IF NOT EXISTS idx_meals_sustainability_score ON meals (sustainability_score);
CREATE INDEX IF NOT EXISTS idx_ingredients_is_deleted ON ingredients (is_deleted);
CREATE INDEX IF NOT EXISTS idx_user_allergies_allergen_id ON user_allergies (allergen_id);
CREATE INDEX IF NOT EXISTS idx_meal_ingredients_ingredient_id ON meal_ingredients (ingredient_id);
CREATE INDEX IF NOT EXISTS idx_stock_records_ingredient_id ON stock_records (ingredient_id);
CREATE INDEX IF NOT EXISTS idx_stock_records_expiry_date ON stock_records (expiry_date);
CREATE INDEX IF NOT EXISTS idx_ingredient_allergens_ingredient_id ON ingredient_allergens (ingredient_id);
CREATE INDEX IF NOT EXISTS idx_ingredient_allergens_allergen_id ON ingredient_allergens (allergen_id);
CREATE INDEX IF NOT EXISTS idx_meal_sustainability_tags_meal_id ON meal_sustainability_tags (meal_id);
CREATE INDEX IF NOT EXISTS idx_meal_sustainability_tags_tag_id ON meal_sustainability_tags (tag_id);
CREATE INDEX IF NOT EXISTS idx_recommendation_events_user_created_at
	ON recommendation_events (user_id, created_at);
CREATE INDEX IF NOT EXISTS idx_recommendation_events_request_id
	ON recommendation_events (request_id);
CREATE INDEX IF NOT EXISTS idx_recommendation_events_meal_type_created_at
	ON recommendation_events (meal_id, event_type, created_at);
CREATE INDEX IF NOT EXISTS idx_recommendation_events_order_id
	ON recommendation_events (order_id);
CREATE INDEX IF NOT EXISTS idx_auth_sessions_user_id ON auth_sessions (user_id);
CREATE INDEX IF NOT EXISTS idx_auth_sessions_expires_at ON auth_sessions (expires_at);
CREATE INDEX IF NOT EXISTS idx_audit_logs_actor_created_at
	ON audit_logs (actor_user_id, created_at);
CREATE INDEX IF NOT EXISTS idx_sustainability_reports_generated_at
	ON sustainability_reports (generated_at);

COMMIT;
