-- PostgreSQL schema generated from bd_er-CN.md
-- This file is intended to run as an initialization script in Docker.

BEGIN;

-- =============================
-- 1. Users and permissions
-- =============================
CREATE TABLE IF NOT EXISTS users (
	user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	username VARCHAR(100) NOT NULL UNIQUE,
	password_hash VARCHAR(255) NOT NULL,
	role VARCHAR(20) NOT NULL CHECK (role IN ('customer', 'staff', 'admin')),
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS user_preferences (
	user_id BIGINT PRIMARY KEY,
	target_calories INT CHECK (target_calories IS NULL OR target_calories >= 0),
	target_protein INT CHECK (target_protein IS NULL OR target_protein >= 0),
	is_vegetarian BOOLEAN NOT NULL DEFAULT FALSE,
	CONSTRAINT fk_user_preferences_user
		FOREIGN KEY (user_id)
		REFERENCES users (user_id)
		ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS allergens (
	allergen_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS user_allergies (
	user_id BIGINT NOT NULL,
	allergen_id BIGINT NOT NULL,
	PRIMARY KEY (user_id, allergen_id),
	CONSTRAINT fk_user_allergies_user
		FOREIGN KEY (user_id)
		REFERENCES users (user_id)
		ON DELETE CASCADE,
	CONSTRAINT fk_user_allergies_allergen
		FOREIGN KEY (allergen_id)
		REFERENCES allergens (allergen_id)
		ON DELETE RESTRICT
);

-- =============================
-- 2. Meals and ingredients
-- =============================
CREATE TABLE IF NOT EXISTS meals (
	meal_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name VARCHAR(150) NOT NULL,
	description TEXT,
	calories INT CHECK (calories IS NULL OR calories >= 0),
	protein INT CHECK (protein IS NULL OR protein >= 0),
	sustainability_score INT CHECK (sustainability_score IS NULL OR sustainability_score >= 0),
	is_deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS ingredients (
	ingredient_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name VARCHAR(120) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS meal_ingredients (
	meal_id BIGINT NOT NULL,
	ingredient_id BIGINT NOT NULL,
	weight_g INT NOT NULL CHECK (weight_g > 0),
	PRIMARY KEY (meal_id, ingredient_id),
	CONSTRAINT fk_meal_ingredients_meal
		FOREIGN KEY (meal_id)
		REFERENCES meals (meal_id)
		ON DELETE CASCADE,
	CONSTRAINT fk_meal_ingredients_ingredient
		FOREIGN KEY (ingredient_id)
		REFERENCES ingredients (ingredient_id)
		ON DELETE RESTRICT
);

-- =============================
-- 3. Inventory and tags
-- =============================
-- Batch-based stock records: one ingredient can have multiple records with different expiry dates.
CREATE TABLE IF NOT EXISTS stock_records (
	stock_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	ingredient_id BIGINT NOT NULL,
	current_qty_g INT NOT NULL CHECK (current_qty_g >= 0),
	expiry_date DATE,
	CONSTRAINT fk_stock_records_ingredient
		FOREIGN KEY (ingredient_id)
		REFERENCES ingredients (ingredient_id)
		ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ingredient_allergens (
	ingredient_id BIGINT NOT NULL,
	allergen_id BIGINT NOT NULL,
	PRIMARY KEY (ingredient_id, allergen_id),
	CONSTRAINT fk_ingredient_allergens_ingredient
		FOREIGN KEY (ingredient_id)
		REFERENCES ingredients (ingredient_id)
		ON DELETE CASCADE,
	CONSTRAINT fk_ingredient_allergens_allergen
		FOREIGN KEY (allergen_id)
		REFERENCES allergens (allergen_id)
		ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS sustainability_tags (
	tag_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	tag_name VARCHAR(100) NOT NULL UNIQUE,
	score_weight INT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS meal_sustainability_tags (
	meal_id BIGINT NOT NULL,
	tag_id BIGINT NOT NULL,
	PRIMARY KEY (meal_id, tag_id),
	CONSTRAINT fk_meal_sustainability_tags_meal
		FOREIGN KEY (meal_id)
		REFERENCES meals (meal_id)
		ON DELETE CASCADE,
	CONSTRAINT fk_meal_sustainability_tags_tag
		FOREIGN KEY (tag_id)
		REFERENCES sustainability_tags (tag_id)
		ON DELETE RESTRICT
);

-- =============================
-- 4. Orders and order items
-- =============================
CREATE TABLE IF NOT EXISTS orders (
	order_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	user_id BIGINT NOT NULL,
	status VARCHAR(20) NOT NULL DEFAULT 'pending'
		CHECK (status IN ('pending', 'confirmed', 'cancelled')),
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT fk_orders_user
		FOREIGN KEY (user_id)
		REFERENCES users (user_id)
		ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS order_items (
	order_id BIGINT NOT NULL,
	meal_id BIGINT NOT NULL,
	quantity INT NOT NULL CHECK (quantity > 0),
	PRIMARY KEY (order_id, meal_id),
	CONSTRAINT fk_order_items_order
		FOREIGN KEY (order_id)
		REFERENCES orders (order_id)
		ON DELETE CASCADE,
	CONSTRAINT fk_order_items_meal
		FOREIGN KEY (meal_id)
		REFERENCES meals (meal_id)
		ON DELETE RESTRICT
);

-- =============================
-- Supporting indexes for common joins and lookups
-- =============================
CREATE INDEX IF NOT EXISTS idx_orders_user_id ON orders (user_id);
CREATE INDEX IF NOT EXISTS idx_order_items_meal_id ON order_items (meal_id);
CREATE INDEX IF NOT EXISTS idx_user_allergies_allergen_id ON user_allergies (allergen_id);
CREATE INDEX IF NOT EXISTS idx_meal_ingredients_ingredient_id ON meal_ingredients (ingredient_id);
CREATE INDEX IF NOT EXISTS idx_stock_records_ingredient_id ON stock_records (ingredient_id);
CREATE INDEX IF NOT EXISTS idx_stock_records_expiry_date ON stock_records (expiry_date);
CREATE INDEX IF NOT EXISTS idx_ingredient_allergens_allergen_id ON ingredient_allergens (allergen_id);
CREATE INDEX IF NOT EXISTS idx_meal_sustainability_tags_tag_id ON meal_sustainability_tags (tag_id);

COMMIT;
