CREATE TABLE IF NOT EXISTS users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(100) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL CHECK (role IN ('customer', 'staff', 'admin')),
    status VARCHAR(20) NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'disabled')),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS user_preferences (
    user_id BIGINT PRIMARY KEY,
    target_calories INT CHECK (target_calories IS NULL OR target_calories >= 0),
    target_protein INT CHECK (target_protein IS NULL OR target_protein >= 0),
    is_vegetarian BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_user_preferences_user FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS allergens (
    allergen_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS user_allergies (
    user_id BIGINT NOT NULL,
    allergen_id BIGINT NOT NULL,
    PRIMARY KEY (user_id, allergen_id),
    CONSTRAINT fk_user_allergies_user FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE,
    CONSTRAINT fk_user_allergies_allergen FOREIGN KEY (allergen_id) REFERENCES allergens (allergen_id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS meals (
    meal_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    description TEXT,
    calories INT CHECK (calories IS NULL OR calories >= 0),
    protein INT CHECK (protein IS NULL OR protein >= 0),
    sustainability_score INT CHECK (sustainability_score IS NULL OR sustainability_score BETWEEN 0 AND 10),
    image_url VARCHAR(500),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS ingredients (
    ingredient_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL UNIQUE,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS meal_ingredients (
    meal_id BIGINT NOT NULL,
    ingredient_id BIGINT NOT NULL,
    weight_g INT NOT NULL CHECK (weight_g > 0),
    PRIMARY KEY (meal_id, ingredient_id),
    CONSTRAINT fk_meal_ingredients_meal FOREIGN KEY (meal_id) REFERENCES meals (meal_id) ON DELETE CASCADE,
    CONSTRAINT fk_meal_ingredients_ingredient FOREIGN KEY (ingredient_id) REFERENCES ingredients (ingredient_id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS stock_records (
    stock_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ingredient_id BIGINT NOT NULL,
    current_qty_g INT NOT NULL CHECK (current_qty_g >= 0),
    expiry_date DATE,
    CONSTRAINT fk_stock_records_ingredient FOREIGN KEY (ingredient_id) REFERENCES ingredients (ingredient_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ingredient_allergens (
    ingredient_id BIGINT NOT NULL,
    allergen_id BIGINT NOT NULL,
    PRIMARY KEY (ingredient_id, allergen_id),
    CONSTRAINT fk_ingredient_allergens_ingredient FOREIGN KEY (ingredient_id) REFERENCES ingredients (ingredient_id) ON DELETE CASCADE,
    CONSTRAINT fk_ingredient_allergens_allergen FOREIGN KEY (allergen_id) REFERENCES allergens (allergen_id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS sustainability_tags (
    tag_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tag_name VARCHAR(100) NOT NULL UNIQUE,
    score_weight INT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS meal_sustainability_tags (
    meal_id BIGINT NOT NULL,
    tag_id BIGINT NOT NULL,
    PRIMARY KEY (meal_id, tag_id),
    CONSTRAINT fk_meal_sustainability_tags_meal FOREIGN KEY (meal_id) REFERENCES meals (meal_id) ON DELETE CASCADE,
    CONSTRAINT fk_meal_sustainability_tags_tag FOREIGN KEY (tag_id) REFERENCES sustainability_tags (tag_id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS orders (
    order_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    recommendation_request_id VARCHAR(64),
    status VARCHAR(20) NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'confirmed', 'cancelled')),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    confirmed_at TIMESTAMP,
    cancelled_at TIMESTAMP,
    CONSTRAINT fk_orders_user FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS order_items (
    order_id BIGINT NOT NULL,
    meal_id BIGINT NOT NULL,
    quantity INT NOT NULL CHECK (quantity > 0),
    meal_name_snapshot VARCHAR(150),
    calories_snapshot INT CHECK (calories_snapshot IS NULL OR calories_snapshot >= 0),
    protein_snapshot INT CHECK (protein_snapshot IS NULL OR protein_snapshot >= 0),
    sustainability_score_snapshot INT CHECK (sustainability_score_snapshot IS NULL OR sustainability_score_snapshot BETWEEN 0 AND 10),
    image_url_snapshot VARCHAR(500),
    PRIMARY KEY (order_id, meal_id),
    CONSTRAINT fk_order_items_order FOREIGN KEY (order_id) REFERENCES orders (order_id) ON DELETE CASCADE,
    CONSTRAINT fk_order_items_meal FOREIGN KEY (meal_id) REFERENCES meals (meal_id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS recommendation_events (
    event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id VARCHAR(64) NOT NULL,
    user_id BIGINT NOT NULL,
    meal_id BIGINT NOT NULL,
    event_type VARCHAR(20) NOT NULL CHECK (event_type IN ('exposure', 'click', 'selected')),
    rank_position INT CHECK (rank_position IS NULL OR rank_position > 0),
    order_id BIGINT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_recommendation_events_user FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE,
    CONSTRAINT fk_recommendation_events_meal FOREIGN KEY (meal_id) REFERENCES meals (meal_id) ON DELETE RESTRICT,
    CONSTRAINT fk_recommendation_events_order FOREIGN KEY (order_id) REFERENCES orders (order_id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS auth_sessions (
    session_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    token_hash VARCHAR(255) NOT NULL UNIQUE,
    issued_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMP NOT NULL,
    revoked_at TIMESTAMP,
    CONSTRAINT fk_auth_sessions_user FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS audit_logs (
    audit_log_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_user_id BIGINT,
    action VARCHAR(100) NOT NULL,
    target_type VARCHAR(50),
    target_id VARCHAR(100),
    details VARCHAR(10000) NOT NULL DEFAULT '{}',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_audit_logs_actor FOREIGN KEY (actor_user_id) REFERENCES users (user_id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS sustainability_reports (
    report_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    summary TEXT NOT NULL,
    report_data VARCHAR(10000) NOT NULL DEFAULT '{}',
    generated_by BIGINT,
    range_start DATE,
    range_end DATE,
    generated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_sustainability_reports_user FOREIGN KEY (generated_by) REFERENCES users (user_id) ON DELETE SET NULL
);
