spring.application.name=backend

spring.datasource.url=jdbc:postgresql://127.0.0.1:55432/meal_recommendation
spring.datasource.username=meal_user
spring.datasource.password=meal_password
spring.datasource.driver-class-name=org.postgresql.Driver

mybatis-plus.configuration.map-underscore-to-camel-case=true
mybatis-plus.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl